config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tours/index'
  get 'tours/show'
  get 'tours/create'
  get '/tours/:id/bookings/index_user', to: 'bookings#index_user'
  patch '/tours/:id/bookings/confirm', to: 'bookings#confirm', as: :booking_confirm
  patch '/tours/:id/bookings/destroy', to: 'bookings#destroy', as: :booking_destroy
  patch '/tours/:id', to: 'tours#change_tour_status', as: :tour_status
  delete '/tours/:id', to: 'tours#destroy', as: :tour_destroy

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours, only: [:new, :edit, :index, :show, :create,] do
    resources :bookings, only: [:create, :destroy]
  end
  resources :bookings, only: [:index, :index_user]
  resources :users, only: [:show]
    # /
    # /tours
    # /tours/:id/bookings
    # /users/:id
    # /bookings/:id/
    # /users/:id/
    # /users/:id/edit
    # /users/:id/tours
    # /users/:id/tours
    # /users/:id/tours/new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user


  def has_spots?
    self.limit_of_people > Booking.where(tour: self).length
  end

  def has_bookings?
    Booking.where(tour: self).length != 0
  end

  def active?
    self.status?
  end

  def colour
    if self.status?
      "warning"
    else
      "success"
    end
  end

  def toggle_status!
    if self.active?
      self.status = false
    else
      self.status = true
    end
    self.save!
  end

  has_one_attached :photo

  validates :title, :description, :limit_of_people, :price, :duration, :destination, :photo, presence: { message: "must be given please" }
  validates :title, :description, length: { minimum: 4 }
  validates :description, length: { maximum: 500 }
  validates :limit_of_people, :price, :duration, numericality: { only_integer: true }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
                  against: [ :title, :description ],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:tour_guide])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:tour_guide])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @allbookings = Booking.all
    @allbookings = policy_scope(Booking).where(user: current_user)
  end

  def create
    @tour = Tour.find(params[:tour_id])
    Booking.where(tour: @tour)
    @booking = Booking.new
    authorize @booking
    @booking.user = current_user
    @booking.tour = @tour
    @booking.status = "Pending confirmation"
    @booking.save
    redirect_to tour_path(@tour)
  end

  def destroy
    @tour = Tour.find(params[:tour_id])
    @booking = Booking.find(params[:id])
    authorize @booking
    Booking.delete(@booking.id)
    redirect_to tour_path(@tour)
  end

  def confirm
    @tour = Tour.find(params[:id])
    @booking = Booking.find(params[:format])
    authorize @booking
    @booking.status = "Confirmed"
    @booking.save
    redirect_to tour_path(@tour)
  end

  private

  def booking_params
    params.require(:booking).permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @tour = Tour.new
    @tours = Tour.all
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :destroy, :change_tour_status]

  def index
    @query = params[:query]
    if params[:query]
      @tours = policy_scope(Tour).search_by_title_and_description(params[:query])
    elsif current_user.tour_guide
      @tours = policy_scope(Tour).where(user: current_user)
    else
      @tours = policy_scope(Tour)
    end
  end

  def show
    authorize @tour
  end

  def new
    @tour = Tour.new
    authorize @tour
  end

  def edit
    authorize @tour
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user
    authorize @tour
    if @tour.save
      redirect_to tours_path
    else
      render :new
    end
  end

  def change_tour_status
    authorize @tour
    if @tour.active?
      @tour.status = false
    else
      @tour.status = true
    end
    @tour.save
    redirect_to tour_path(@tour)
  end

  def destroy
    set_tour
    @tour.bookings.each do |booking|
      Booking.delete(booking.id)
    end
    Tour.delete(@tour.id)
    authorize @tour
    redirect_to tours_path
  end

  private

  def set_tour
    @tour = Tour.find(params[:id])
  end

  def tour_params
    params.require(:tour).permit(:title, :description, :limit_of_people, :price, :starting_time, :duration, :status, :destination, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookings = current_user.bookings
    @tours = current_user.tours if current_user.tour_guide
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tours_helper.rb
module ToursHelper
  def link_to_toggle_tour_active(tour)
    @tour = Tour.find(params[:id])
    url = tour_status_path(tour)

    if tour.active?
      link_to_with_icon('icon-star', 'active', url, {
        method: 'PATCH',
        remote: true,
        class: 'active btn btn-primary',
      })
    else
      link_to_with_icon('icon-star', 'active', url, {
        method: 'PATCH',
        remote: true,
        class: 'active btn',
      })
    end
  end

  def link_to_with_icon(icon_css, title, url, options = {})
    icon = content_tag(:i, nil, class: icon_css)
    title_with_icon = icon << ' '.html_safe << h(title)
    link_to(title_with_icon, url, options)
  end
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>

<% @bookings.each do |booking|%>
  <%= booking.status %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourGuide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>


    <!---Navbar --->

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>

          <%= image_tag "Logo.png" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Tours", tours_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
            <!---
            <li class="nav-item">
              <%= link_to "Become a Guide", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", "#", class: "nav-link" %>
            </li>
          <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
              </div>
            </li> --->
          </ul>
        </div>
      </div>
    </div>
    <div class="container navbar-margin">
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>

    <!---  Footer --->

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>

  </body>

</html>

app/views/pages/home.html.erb
<!---SEARCH -->
<%= form_tag tours_path, method: :get do %>
  <div id="search-bar" class="my-5 input-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a tour"
    %>
    <%= submit_tag "Search", class: "btn btn-secondary" %>
  </div>
<% end %>

<!---BANNER -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner_pic.jpg') %>);">
  <div class="container">
    <h1>Redefine your adventure</h1>
    <p>let yourself be guided through your adventures by <strong>locals</strong> all over the world!</p>
    <%= link_to "Apply now", new_user_session_path, id: "cta" %>
  </div>
</div>

<!---Most popular tours CARDS -->

<h2 class="my-4">Most popular tours</h2>

<div class="card-container">
<% @tours.each do |tour| %>
  <%= link_to tour_path(tour.id), class:"card-link" do%>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('pao_de_acucar.jpg') %>)">
      <%= tour.title %>
    </div>
  <% end %>
<% end %>
</div>

<!---Choose your favorite type of tour CARDS -->

<h2 class="my-4">Choose your favorite type of tour</h2>

<div class="card-container">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('pao_de_acucar.jpg') %>)">
    <%= link_to tours_path(:query => "hiking"), class:"card-link" do%>
      Hiking
    <%end%>
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('diving.jpg') %>)">
    <%= link_to tours_path(:query => "diving"), class:"card-link" do%>
      Diving
    <%end%>
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('citytour.jpg') %>)">
    <%= link_to tours_path(:query => "city"), class:"card-link" do%>
      City Tours
    <%end%>
  </div>
  <!---<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('cristo.jpg') %>)">
    <%= link_to tours_path(:query => "wellness"), class:"card-link" do%>
      Wellness
    <%end%>
  </div>--->
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/tours/index.html.erb
<h1 class="my-5">Find your next tour</h1>
<div class="cards">
  <% @tours.each do |tour|%>
    <div class="tour-card p-3">
      <%= cl_image_tag tour.photo.key, height: 300, width: 400, crop: :fill, class: "mb-3"%>
      <div>
        <h2 class="tour-title"><%= tour.title %></h2>
        <p class="tour-description"><%= tour.description %></p>
      </div>
      <div class="card-bottom mt-5">
        <%= link_to "More info", tour_path(tour), class: "btn-tour-show" %>
        <h3 class="tour-price">$ <%= tour.price %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/new.html.erb
<h1>Add your tour</h1>

<%= simple_form_for(@tour) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :limit_of_people %>
  <%= f.input :price %>
  <%= f.input :starting_time %>
  <%= f.input :duration %>
  <%= f.input :destination %>
  <%= f.input :photo, as: :file %>
  <%= f.input :status %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/tours/show.html.erb
<div class="container">
  <div class="card mb-4">
    <div class="row no-gutters">
      <div class="col-md-8 tour-img">
        <%= cl_image_tag @tour.photo.key, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h5 class="card-title"><%= @tour.title %></h5>
          <h5 class="card-text"><%= @tour.description %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Limit of <%= @tour.limit_of_people%> people</li>
          <li class="list-group-item">$ <%= @tour.price%></li>
          <li class="list-group-item">Every day at <%= @tour.starting_time.hour%>h</li>
          <li class="list-group-item">Duration of <%= @tour.duration%> hour(s)</li>
          <li class="list-group-item">Meeting at <%= @tour.destination%></li>
        </ul>
      </div>
    </div>
  </div>
</div>



<h2>Bookings:</h2>
  <% if user_signed_in? && current_user.tour_guide? == false %>
    <% if @tour.active? == false %>
      <p><i>This tour is currently not taking any new bookings.</i></p>
    <% elsif @tour.has_spots? %>
        <li class="btn btn-info">
          <%= link_to "Book this tour", tour_bookings_path(@tour, anchor: "bookings-list"), method:"POST", class: "nav-link" %>
        </li>
        <br>
    <% else %>
      <p style="color:red;"><i>Sorry, this tour is full!</i></p>
    <% end %>

    <ul style="list-style: none;" id="bookings-list">
      <% @tour.bookings.each do |booking| %>
        <% if booking.user_id == current_user.id %>
          <% if booking.status == "Confirmed" %>
            <li><div class="flash flash-success fade show">
          <% else %>
            <li><div class="flash flash-danger fade show">
          <% end %>
          <u>Booking <%= booking.id %></u>: <%= booking.status %>
              <%= link_to "Cancel", tour_booking_path(@tour, booking.id, anchor: "bookings-list"), method:"DELETE", class: "booking-link" %>
          </div></li>
        <%end%>
      <%end%>
    </ul>
  <% elsif user_signed_in? && current_user.tour_guide? == true %>
    <% if @tour.status? == false %>
    <p style="color:red"><i>Activate this tour below to receive new bookings.</i></p>
    <% end %>
    <% if @tour.has_bookings? == false %>
      <p>No bookings yet!</p>
    <% elsif @tour.has_spots? %>
      <p>You have the following bookings for this tour:</p>
    <% else %>
      <p>Congrats <%= current_user.first_name %>! Your tour is <b>sold out</b>! You have the following bookings for this tour:</p>
    <% end %>
    <ul style="list-style: none;" id="bookings-list">
      <% @tour.bookings.each do |booking| %>
        <% if booking.status == "Confirmed" %>
        <li><div class="flash flash-success fade show">
        <% else %>
        <li><div class="flash flash-danger fade show">
      <% end %>
        <u>Booking <%= booking.id %></u>: <%= User.find(booking.user_id).first_name %> <%= User.find(booking.user_id).last_name %> - <%= booking.status %>
          <% if booking.status == "Pending confirmation" %>
              <%= link_to "Confirm booking", booking_confirm_path(@tour, booking.id, anchor: "bookings-list"), method:"PATCH", class: "booking-link", id:"booking-unconfirmed" %>
          <%end%>
            <%= link_to "Cancel", tour_booking_path(@tour, booking.id, anchor: "bookings-list"), method:"DELETE", class: "booking-link" %>
        </div></li>
      <%end%>
            <button class="btn btn-<%=@tour.colour%>" onclick="toggle(this)" ><%=link_to "#{ @tour.status ? 'Deactivate this tour' : 'Activate this tour' }", tour_status_path(@tour, anchor: "bookings-list"), method:"PATCH", class: "nav-link"  %></button>

          <li class="btn btn-danger" >
            <%=link_to "Cancel this tour", tour_destroy_path(@tour), method:"DELETE", data: { confirm: 'Are you sure you want to cancel this tour? This will permanently delete all existing bookings.' }, class: "nav-link"  %>
          </li>
        <br>
        <br>
<% else %>
  <p>You need to sign in to see your bookings</p>
<% end %>
<%= link_to 'Back', tours_path %> |

<script src="../lib/toggle.js"></script>

app/views/users/show.html.erb
<h1>User profile</h1>

<%= current_user.email%>
<% if current_user.tour_guide %>
<% @tours.each do |tour|%>
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= tour.title%></h2>
      <p><%= tour.description %></p>
    </div>
    <h2 class="card-trip-pricing"><%= tour.price %></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
<%end%>
<% else %>
<% @bookings.each do |booking|%>
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= booking.tour.title%></h2>
    </div>
    <h2 class="card-trip-pricing"><%= booking.status%></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
<%end%>
<% end %>

<% if policy(Tour).create? %>
  <%= link_to "New tour", new_tour_path %>
<% end %>